%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,11,27},{12,13,35}}

-ifndef(yawp_sample_func).
-define(yawp_sample_func, true).

-define(yawp_sample_func_gpb_version, "3.21.0").

-ifndef('YAWP.SAMPLE.FUNC.CALL_PB_H').
-define('YAWP.SAMPLE.FUNC.CALL_PB_H', true).
-record('yawp.sample.func.Call',
        {
        }).
-endif.

-ifndef('YAWP.SAMPLE.TYPE.TYPE_PB_H').
-define('YAWP.SAMPLE.TYPE.TYPE_PB_H', true).
-record('yawp.sample.type.Type',
        {
        }).
-endif.

-endif.
