%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,11,27},{12,13,35}}

-ifndef(yawp_sample_type).
-define(yawp_sample_type, true).

-define(yawp_sample_type_gpb_version, "3.21.0").

-ifndef('YAWP.SAMPLE.TYPE.TYPE_PB_H').
-define('YAWP.SAMPLE.TYPE.TYPE_PB_H', true).
-record('yawp.sample.type.Type',
        {
        }).
-endif.

-endif.
